/**********************************************************************************************************************
 * \file SPI_CPU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SPI_CPU.h"
#include "IfxPort.h"
#include "ASCLIN_UART.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* QSPI modules */
//#define QSPI1_MASTER                &MODULE_QSPI1   /* SPI Master module                                            */
#define QSPI3_SLAVE                 &MODULE_QSPI3   /* SPI Slave module                                             */

/* LED port pin */
//#define LED1                        &MODULE_P00,5
#define LED1                        &MODULE_P10,2
//        IfxPort_togglePin(&MODULE_P00,5);

#define MASTER_CHANNEL_BAUDRATE     1000000         /* Master channel baud rate                                     */

#define ISR_PRIORITY_SLAVE_TX       10
#define ISR_PRIORITY_SLAVE_RX       11
#define ISR_PRIORITY_SLAVE_ER       12

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
qspiComm g_qspi;
static volatile uint32 rcvdData = 0;
static volatile uint8 SPIBuf = 0;
volatile uint8 g_SPIFlag = 0;
static volatile uint8 SPIArr[4] = {0,};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initQSPI3Slave(void);
void initQSPI3SlaveBuffers(void);
void initLED(void);
/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(slaveTxISR, 0, ISR_PRIORITY_SLAVE_TX);                    /* SPI Slave ISR for transmit data          */
IFX_INTERRUPT(slaveRxISR, 0, ISR_PRIORITY_SLAVE_RX);                    /* SPI Slave ISR for receive data           */
IFX_INTERRUPT(slaveErISR, 0, ISR_PRIORITY_SLAVE_ER);                    /* SPI Slave ISR for error                  */

void slaveTxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiSlave_isrTransmit(&g_qspi.spiSlave);
}

void slaveRxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiSlave_isrReceive(&g_qspi.spiSlave);

    rcvdData = IfxQspi_readReceiveFifo(g_qspi.spiSlave.qspi);
    SPIBuf = rcvdData & 0xFF;
    g_SPIFlag = 1;

    IfxQspi_writeTransmitFifo(g_qspi.spiSlave.qspi, SPIBuf);
}

void slaveErISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiSlave_isrError(&g_qspi.spiSlave);
}

void initQSPI3Slave(void)
{
    IfxQspi_SpiSlave_Config spiSlaveConfig;                             /* Define the Slave configuration           */
    IfxQspi_SpiSlave_initModuleConfig(&spiSlaveConfig, QSPI3_SLAVE);    /* Initialize it with default values        */

    const IfxQspi_SpiSlave_Pins qspi3SlavePins = {
        &IfxQspi3_SCLKA_P02_7_IN, IfxPort_InputMode_pullDown,           /* SCLK Pin9                      (CLK)     */
        &IfxQspi3_MTSRA_P02_6_IN, IfxPort_InputMode_pullDown,           /* MasterTransmitSlaveReceive pin8(MOSI)    */
        &IfxQspi3_MRST_P02_5_OUT, IfxPort_OutputMode_pushPull,          /* MasterReceiveSlaveTransmit pin7(MISO)    */
        &IfxQspi3_SLSIA_P02_4_IN, IfxPort_InputMode_pullDown,           /* SlaveSelect Pin6               (CS)      */
        IfxPort_PadDriver_cmosAutomotiveSpeed3                          /* Pad driver mode                          */
    };
    spiSlaveConfig.pins = &qspi3SlavePins;                              /* Assign Slave port pins                   */

    spiSlaveConfig.base.txPriority = ISR_PRIORITY_SLAVE_TX;
    spiSlaveConfig.base.rxPriority = ISR_PRIORITY_SLAVE_RX;
    spiSlaveConfig.base.erPriority = ISR_PRIORITY_SLAVE_ER;
    spiSlaveConfig.base.isrProvider = IfxSrc_Tos_cpu0;

    IfxQspi_SpiSlave_initModule(&g_qspi.spiSlave, &spiSlaveConfig);
}

void initQSPI3SlaveBuffers(void)
{
    for (uint8 i = 0; i < SPI_BUFFER_SIZE; i++)
    {
        g_qspi.spiBuffers.spiSlaveTxBuffer[i] = 0x50;                      /* Clear TX Slave Buffer                    */
        g_qspi.spiBuffers.spiSlaveRxBuffer[i] = 0x50;                      /* Clear RX Slave Buffer                    */
    }
    g_qspi.spiSlave.rxJob.data = &g_qspi.spiBuffers.spiSlaveRxBuffer[0];
    g_qspi.spiSlave.txJob.data = &g_qspi.spiBuffers.spiSlaveTxBuffer[0];
    g_qspi.spiSlave.txJob.remaining = SPI_BUFFER_SIZE;
}

void initLED(void)
{
    IfxPort_setPinModeOutput(LED1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_togglePin(&MODULE_P00,5);
}

void initQSPI(void)
{
//    initLED();
    initQSPI3Slave();
    initQSPI3SlaveBuffers();
}

void transferData(uint8 data[], uint8 size)
{
    while(IfxQspi_SpiSlave_getStatus(&g_qspi.spiSlave) == SpiIf_Status_busy)
    {

    }
    IfxQspi_SpiSlave_exchange(&g_qspi.spiSlave, NULL_PTR, &g_qspi.spiBuffers.spiSlaveRxBuffer[0], SPI_BUFFER_SIZE);
}

uint8 getSPIBuf(void)
{
    return SPIBuf;
}

//void setSPIBuf(uint8 value) {
//    SPIBuf = value;
//}
//
