/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdint.h>
#include "memoryshared.h"
#include "ASCLIN_UART.h"
#include "GlobalVar.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

const char *songTitles[] = {"Live my Life by Aespa",   // SongFlag % 5 == 1
        "Zombie by DAY6",          // SongFlag % 5 == 2
        "Welcome to the Show",     // SongFlag % 5 == 3
        "Bubble Gum by NewJeans",  // SongFlag % 5 == 4
        "Drowning by Artist"       // SongFlag % 5 == 0
        };

int core1_main (void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    lcd_init();
//
//    lcd_typewriter_effect("Hello!", 150);
//    lcd_blink_text("Welcome!", 3, 500);
//
//    lcd_scroll_horizontal("Hello World!", 1, 200); // 왼쪽에서 오른쪽
//    lcd_scroll_horizontal("Hello World!", 0, 200); // 오른쪽에서 왼쪽

    while (1)
    {
        asepa("Live My Life ");

        Day6("Welcome to the Show ");

        Day7(" * Z.O.M.B.I.E *  ");

        New(" ** Bubble Gum **    ");

        NMIX(" *** O.O ***   ");

    }
    return 1;

}

