/**********************************************************************************************************************
 * \file Forwarding_Handler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Forwarding.h"
#include "ASCLIN_UART.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile CANTask CANtaskList[MAX_TASKS];
volatile uint8 CANBuf[4];

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
void send0x100(uint8, uint8); // IGN
void send0x300(uint8, uint8); // Seat
void send0x301(uint8, uint8); // SHV
void send0x302(uint8, uint8); // Win
void send0x303(uint8, uint8); // MP3
void registerTask(void (*taskFunc)(uint8, uint8), uint16 CANID);
void setSignalValue(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void initForwarding()
{
    registerTask(send0x100, 0x100);
    registerTask(send0x300, 0x300);
    registerTask(send0x301, 0x301);
    registerTask(send0x302, 0x302);
    registerTask(send0x303, 0x303);
    setSignalValue();
}

void registerTask(void (*taskFunc)(uint8, uint8), uint16 CANID)
{
    for (int i = 0; i < MAX_TASKS; i++)
    {
        if (CANtaskList[i].taskFunc == 0)
        {
            CANtaskList[i].taskFunc = taskFunc;
            CANtaskList[i].CANID = CANID;
            break;
        }
    }
}

void forwardingSPI()
{
    volatile uint16 CANID = 0;
    volatile uint8 CANSigID = 0;
    volatile uint8 CANData = 0;

    CANID = (CANBuf[0] << 8) | CANBuf[1];
    CANSigID = CANBuf[2];
    CANData = CANBuf[3];

    for (uint8 i = 0; i < MAX_TASKS; ++i)
    {
        if (CANtaskList[i].taskFunc != NULL && CANtaskList[i].CANID == CANID)
        {
            IfxPort_togglePin(&MODULE_P10, 2);
            CANtaskList[i].taskFunc(CANSigID, CANData);
        }
    }

    transmitCanMessage(0x100);
    transmitCanMessage(0x300);
    transmitCanMessage(0x301);
    transmitCanMessage(0x302);
    transmitCanMessage(0x303);
    setSignalValue();
}

void send0x100(uint8 sigID, uint8 data) // IGN
{
    switch(sigID)
    {
        case 1:
            g_canSignalData_Tx.IGN1 = data;
            break;
        default:
            g_canSignalData_Tx.IGN1 = 0;
            break;
    }
}

void send0x300(uint8 sigID, uint8 data) // Seat
{
    switch(sigID)
    {
        case 1:
            g_canSignalData_Tx.Seat_RelaxMode = data;
            g_canSignalData_Tx.Move_FrontSeat = 0;
            g_canSignalData_Tx.Fold_FrontSeat = 0;
            g_canSignalData_Tx.Fold_BackSeat = 0;
            break;
        case 2:
            g_canSignalData_Tx.Move_FrontSeat = data;
            break;
        case 3:
            g_canSignalData_Tx.Fold_FrontSeat = data;
            break;
        case 4:
            g_canSignalData_Tx.Fold_BackSeat = data;
            break;
        default:
            g_canSignalData_Tx.Seat_RelaxMode = 0;
            g_canSignalData_Tx.Move_FrontSeat = 0;
            g_canSignalData_Tx.Fold_FrontSeat = 0;
            g_canSignalData_Tx.Fold_BackSeat = 0;
            break;
    }
}

void send0x301(uint8 sigID, uint8 data) // SHV
{
    switch(sigID)
    {
        case 1:
            g_canSignalData_Tx.Cush_Heat = data;
            break;
        case 2:
            g_canSignalData_Tx.Back_Heat = data;
            break;
        case 3:
            g_canSignalData_Tx.SHV_VentCmd = data;
            break;
        default:
            g_canSignalData_Tx.Cush_Heat = 0;
            g_canSignalData_Tx.Back_Heat = 0;
            g_canSignalData_Tx.SHV_VentCmd = 0;
            break;
    }
}

void send0x302(uint8 sigID, uint8 data) // Win
{
    switch(sigID)
    {
        case 1:
//            g_canSignalData_Tx.WindowUp = data;
            g_canSignalData_Tx.WindowDown = data;
            break;
        case 2:
//            g_canSignalData_Tx.WindowDown = data;
            g_canSignalData_Tx.WindowUp = data;
            break;
        default:
            g_canSignalData_Tx.WindowUp = 0;
            g_canSignalData_Tx.WindowDown = 0;
            break;
    }
}

void send0x303(uint8 sigID, uint8 data) // MP3
{
    switch(sigID)
    {
        case 1:
            g_canSignalData_Tx.MP3_Cmd = data;
            g_canSignalData_Tx.MP3_Parameter = 0;
            break;
        case 2:
            g_canSignalData_Tx.MP3_Cmd = 0x06;
            g_canSignalData_Tx.MP3_Parameter = data;
            break;
        case 3:
            g_canSignalData_Tx.MP3_Cmd = 0x07;
            g_canSignalData_Tx.MP3_Parameter = data;
            break;
        case 4:
            g_canSignalData_Tx.MP3_Cmd = 0x08;
            g_canSignalData_Tx.MP3_Parameter = data;
            break;
        default:
            g_canSignalData_Tx.MP3_Cmd = 0;
            g_canSignalData_Tx.MP3_Parameter = 0;
            break;
    }
}

void setSignalValue(void)
{
    //0x100
    g_canSignalData_Tx.IGN1 = 1;

    //0x300
//    g_canSignalData_Tx.Seat_RelaxMode = 0;
//    g_canSignalData_Tx.Move_FrontSeat = 0;
//    g_canSignalData_Tx.Fold_FrontSeat = 0;
//    g_canSignalData_Tx.Fold_BackSeat = 0;

    //0x301
//    g_canSignalData_Tx.Cush_Heat = 0;
//    g_canSignalData_Tx.Back_Heat = 0;
//    g_canSignalData_Tx.SHV_VentCmd = 0;

    //0x302
//    g_canSignalData_Tx.WindowUp = 0;
//    g_canSignalData_Tx.WindowDown = 0;

    //0x303
    g_canSignalData_Tx.MP3_Cmd = 0;
    g_canSignalData_Tx.MP3_Parameter = 0;
}
